version: "3"

services:
  app:
    build: .
    env_file: 
      - .env
    links:
      - db
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yet2ksn2018*
      MYSQL_USER: teemo
      MYSQL_PASSWORD: yet2ksn2018*
      MYSQL_ROOT_HOST: "%"
      
